
const W=1280,H=720;
const state={wave:1,zombies:10,baseHp:100,players:{},selectedClass:"soldier",zombieSprites:[],playerSprites:{},gameScene:null};
const waveEl=document.getElementById("wave"),zombieCountEl=document.getElementById("zombieCount"),baseHpEl=document.getElementById("baseHp"),leaderboardEl=document.getElementById("leaderboard"),logEl=document.getElementById("log"),bannerEl=document.getElementById("banner"),playerNameInput=document.getElementById("playerName");
function addLog(t){const r=document.createElement("div");r.textContent=t;logEl.prepend(r)}
function banner(t){bannerEl.textContent=t;bannerEl.animate([{transform:"translateX(-50%) scale(1.05)",opacity:1},{transform:"translateX(-50%) scale(1)",opacity:1}],{duration:250})}
function nameClean(n){return(n||"Viewer").trim().slice(0,18)||"Viewer"}
function classEmoji(c){return c==="medic"?"❤️":c==="engineer"?"🔨":c==="sniper"?"🎯":"🪖"}
function ensurePlayer(name){name=nameClean(name);if(!state.players[name]){state.players[name]={name,cls:state.selectedClass,hp:100,xp:0,kills:0,supplies:0,x:250+Math.random()*170,y:470+Math.random()*105};addLog(`📢 Reinforcement has arrived: ${name}`);banner(`📢 REINFORCEMENT HAS ARRIVED: ${name}`);if(state.gameScene)state.gameScene.spawnPlayer(state.players[name])}return state.players[name]}
class ZAttackScene extends Phaser.Scene{
constructor(){super("ZAttackScene")}
create(){state.gameScene=this;this.add.rectangle(W/2,H/2,W,H,0x142617);this.drawMap();this.safehouse=this.add.container(1040,535);const house=this.add.rectangle(0,0,230,150,0x233225).setStrokeStyle(5,0x7bd77d);const roof=this.add.triangle(0,-88,-132,0,0,-100,132,0,0x5c3922);const label=this.add.text(0,35,"SAFE HOUSE",{fontSize:"26px",fontFamily:"Arial",fontStyle:"bold",color:"#ffffff"}).setOrigin(.5);this.safehouse.add([roof,house,label]);this.add.text(40,34,"ZOMBIE SPAWN",{fontSize:"24px",fontStyle:"bold",color:"#ffb0b0"});this.add.text(40,675,"SURVIVOR AREA",{fontSize:"22px",fontStyle:"bold",color:"#c7f7ff"}).setOrigin(0,1);this.baseBarBack=this.add.rectangle(1040,635,240,18,0x2c2c2c).setOrigin(.5);this.baseBar=this.add.rectangle(920,635,240,18,0x53dd66).setOrigin(0,.5);this.spawnZombies();Object.values(state.players).forEach(p=>this.spawnPlayer(p));this.time.addEvent({delay:7000,loop:true,callback:()=>waveTick()})}
drawMap(){for(let x=0;x<W;x+=64)this.add.line(0,0,x,0,x,H,0x2b3f2c,.35).setOrigin(0);for(let y=0;y<H;y+=64)this.add.line(0,0,0,y,W,y,0x2b3f2c,.35).setOrigin(0);for(let i=0;i<45;i++){const x=Phaser.Math.Between(20,W-20),y=Phaser.Math.Between(85,H-45),c=Phaser.Math.RND.pick([0x274427,0x304d2d,0x1d3522]);this.add.circle(x,y,Phaser.Math.Between(5,15),c,.75)}this.add.rectangle(W/2,360,W-80,260,0x0f1410,.18).setStrokeStyle(2,0x52633d,.7)}
spawnZombies(){state.zombieSprites.forEach(z=>z.destroy());state.zombieSprites=[];const show=Math.min(state.zombies,28);for(let i=0;i<show;i++){const x=Phaser.Math.Between(70,260),y=Phaser.Math.Between(90,330);const z=this.add.container(x,y);const body=this.add.circle(0,0,22,0x73b95b).setStrokeStyle(3,0x1d3419);const head=this.add.circle(0,-24,17,0x8ed47a).setStrokeStyle(3,0x1d3419);const eye1=this.add.circle(-6,-27,3,0xff2f2f);const eye2=this.add.circle(6,-27,3,0xff2f2f);const txt=this.add.text(0,2,"Z",{fontSize:"16px",fontStyle:"bold",color:"#153315"}).setOrigin(.5);z.add([body,head,eye1,eye2,txt]);state.zombieSprites.push(z);this.tweens.add({targets:z,y:y+Phaser.Math.Between(-8,8),duration:600+Math.random()*700,yoyo:true,repeat:-1})}}
spawnPlayer(p){if(state.playerSprites[p.name])return;const c=this.add.container(p.x,p.y);const color=p.cls==="medic"?0xff5c8a:p.cls==="engineer"?0x47c7ff:p.cls==="sniper"?0xffd166:0xc8d7ff;const shadow=this.add.ellipse(0,28,50,15,0x000000,.35);const body=this.add.rectangle(0,0,34,42,color).setStrokeStyle(3,0x111111);const head=this.add.circle(0,-35,17,0xffd2a6).setStrokeStyle(3,0x111111);const label=this.add.text(0,-67,`${classEmoji(p.cls)} ${p.name}`,{fontSize:"15px",fontFamily:"Arial",fontStyle:"bold",color:"#ffffff",backgroundColor:"rgba(0,0,0,.55)",padding:{x:5,y:3}}).setOrigin(.5);const hpBack=this.add.rectangle(0,38,50,7,0x222222);const hp=this.add.rectangle(-25,38,50,7,0x45e66a).setOrigin(0,.5);c.add([shadow,body,head,label,hpBack,hp]);c.hpBar=hp;c.playerName=p.name;state.playerSprites[p.name]=c}
actionMove(p,x,y,color,text){const s=state.playerSprites[p.name];if(!s)return;this.tweens.add({targets:s,x,y,duration:280,yoyo:true,ease:"Sine.easeOut"});this.floatingText(s.x,s.y-80,text,color)}
damageZombie(amount){const z=state.zombieSprites.pop();if(z){this.floatingText(z.x,z.y-30,`-${amount}`,"#ffdd55");this.tweens.add({targets:z,alpha:0,scale:1.5,duration:300,onComplete:()=>z.destroy()})}}
moveZombiesCloser(){state.zombieSprites.forEach(z=>this.tweens.add({targets:z,x:z.x+Phaser.Math.Between(40,75),y:z.y+Phaser.Math.Between(20,55),duration:650,ease:"Sine.easeInOut"}))}
pushZombiesBack(){state.zombieSprites.forEach(z=>this.tweens.add({targets:z,x:Math.max(60,z.x-Phaser.Math.Between(22,45)),duration:280}))}
floatingText(x,y,text,color="#ffffff"){const t=this.add.text(x,y,text,{fontSize:"30px",fontFamily:"Arial",fontStyle:"bold",color,stroke:"#000000",strokeThickness:5}).setOrigin(.5);this.tweens.add({targets:t,y:y-55,alpha:0,duration:850,onComplete:()=>t.destroy()})}
updateBaseBar(){this.baseBar.width=Math.max(0,240*(state.baseHp/100));this.baseBar.fillColor=state.baseHp<35?0xff4f4f:state.baseHp<70?0xffcc4d:0x53dd66}
}
new Phaser.Game({type:Phaser.AUTO,parent:"game",width:W,height:H,backgroundColor:"#101c14",scene:ZAttackScene,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH}});
function doCommand(command){const player=ensurePlayer(playerNameInput.value),scene=state.gameScene;if(command==="join"){addLog(`🧍 ${player.name} joined as ${player.cls}.`)}
if(command==="fight"){const base=player.cls==="soldier"?3:player.cls==="sniper"?4:2,kills=Phaser.Math.Between(1,base);state.zombies=Math.max(0,state.zombies-kills);player.kills+=kills;player.xp+=kills*12;addLog(`⚔️ ${player.name} defeated ${kills} zombie(s).`);banner(`⚔️ ${player.name} attacks the horde!`);scene.actionMove(player,620,350,"#ffdd55",`-${kills*10}`);for(let i=0;i<kills;i++)scene.damageZombie(10);scene.pushZombiesBack()}
if(command==="heal"){const heal=player.cls==="medic"?35:20;player.hp=Math.min(100,player.hp+heal);player.xp+=7;addLog(`❤️ ${player.name} healed +${heal} HP.`);banner(`❤️ ${player.name} heals the squad!`);scene.actionMove(player,player.x,player.y-35,"#77ff99",`+${heal}`)}
if(command==="search"){const supplies=Phaser.Math.Between(1,5);player.supplies+=supplies;player.xp+=supplies*6;addLog(`🎒 ${player.name} found ${supplies} supplies.`);banner(`🎒 ${player.name} found supplies!`);scene.actionMove(player,520,460,"#9ee7ff",`+${supplies} supplies`)}
if(command==="build"){const repair=player.cls==="engineer"?Phaser.Math.Between(15,25):Phaser.Math.Between(6,13);state.baseHp=Math.min(100,state.baseHp+repair);player.xp+=repair;addLog(`🔨 ${player.name} repaired base +${repair} HP.`);banner(`🔨 ${player.name} repairs the base!`);scene.actionMove(player,1000,520,"#7dff8c",`+${repair} HP`)}
if(command==="run"){player.xp+=4;addLog(`🏃 ${player.name} retreated safely.`);banner(`🏃 ${player.name} retreats to safety.`);scene.actionMove(player,315,560,"#ffffff","SAFE")}
if(command==="boost"){const kills=Phaser.Math.Between(4,8);state.zombies=Math.max(0,state.zombies-kills);player.kills+=kills;player.xp+=kills*15;addLog(`⚡ ${player.name} used BOOST and cleared ${kills} zombies!`);banner(`⚡ BOOST! ${player.name} clears the horde!`);scene.actionMove(player,670,320,"#d99cff",`-${kills*12}`);for(let i=0;i<kills;i++)scene.damageZombie(12);scene.pushZombiesBack()}
if(state.zombies<=0)clearWave();updateUI()}
function clearWave(){addLog(`✅ Wave ${state.wave} cleared!`);banner(`✅ WAVE ${state.wave} CLEARED!`);state.wave++;state.zombies=8+state.wave*5;Object.values(state.players).forEach(p=>p.xp+=15);if(state.wave%5===0){state.zombies+=12;addLog("👹 Boss wave incoming!");banner("👹 BOSS WAVE INCOMING!")}if(state.gameScene)state.gameScene.spawnZombies()}
function waveTick(){if(!state.gameScene)return;if(state.zombies>0){state.gameScene.moveZombiesCloser();const damage=Math.min(28,Math.floor(state.zombies*(.35+state.wave*.03)));state.baseHp=Math.max(0,state.baseHp-damage);addLog(`🧟 Zombies advanced and damaged base -${damage} HP.`);banner("🧟 ZOMBIES ARE PUSHING FORWARD!")}if(state.baseHp<=0){addLog("🚨 Safe house destroyed. Resetting camp.");banner("🚨 SAFE HOUSE DESTROYED — RESET!");state.wave=1;state.zombies=10;state.baseHp=100;if(state.gameScene)state.gameScene.spawnZombies()}updateUI()}
function updateUI(){waveEl.textContent=state.wave;zombieCountEl.textContent=state.zombies;baseHpEl.textContent=state.baseHp;if(state.gameScene)state.gameScene.updateBaseBar();leaderboardEl.innerHTML="";Object.values(state.players).sort((a,b)=>b.xp-a.xp||b.kills-a.kills).slice(0,10).forEach(p=>{const li=document.createElement("li");li.textContent=`${classEmoji(p.cls)} ${p.name} — XP ${p.xp}, Kills ${p.kills}`;leaderboardEl.appendChild(li)})}
document.querySelectorAll("[data-command]").forEach(btn=>btn.addEventListener("click",()=>doCommand(btn.dataset.command)));
document.querySelectorAll("[data-class]").forEach(btn=>btn.addEventListener("click",()=>{state.selectedClass=btn.dataset.class;banner(`Class selected: ${state.selectedClass.toUpperCase()}`);addLog(`🎯 New players will join as ${state.selectedClass}.`)}));
addLog("🎮 ZAttack v3 loaded. Enter name and click Reinforcement Join.");updateUI();
